const types = @import("types");

const ProblemDetails = struct {
    /// A URI reference [RFC3986] that identifies the problem type.
    type: []u8,

    /// A short, human-readable summary of the problem type.
    title: []u8,

    /// The HTTP status code [RFC7231, 6] generated by the origin server for
    /// this occurrence of the problem.
    status: types.UnsignedInt,

    /// A human-readable explanation specific to this occurrence of the problem.
    detail: []u8,

    /// A URI reference that identifies the specific occurrence of the problem.
    instance: []u8,
};
